let icons = ['add to calendar icon',
    'address book icon',
    'address book outline icon',
    'address card icon',
    'address card outline icon',
    'alarm icon',
    'alarm mute icon',
    'alarm mute outline icon',
    'alarm outline icon',
    'at icon',
    'browser icon',
    'bug icon',
    'calendar icon',
    'calendar outline icon',
    'checked calendar icon',
    'cloud icon',
    'code icon',
    'comment icon',
    'comment outline icon',
    'comments icon',
    'comments icon',
    'comments outline icon',
    'copyright icon',
    'creative commons icon',
    'dashboard icon',
    'delete calendar icon',
    'external icon',
    'external icon',
    'external square icon',
    'eyedropper icon',
    'feed icon',
    'find icon',
    'hand pointer icon',
    'handshake icon',
    'hashtag icon',
    'heartbeat icon',
    'history icon',
    'home icon',
    'hourglass empty icon',
    'hourglass end icon',
    'hourglass full icon',
    'hourglass half icon',
    'hourglass start icon',
    'id badge icon',
    'id card icon',
    'id card outline icon',
    'idea icon',
    'image icon',
    'inbox icon',
    'industry icon',
    'lab icon',
    'mail icon',
    'mail outline icon',
    'mail square icon',
    'mouse pointer icon',
    'open envelope icon',
    'open envelope outline icon',
    'options icon',
    'paint brush icon',
    'payment icon',
    'percent icon',
    'podcast icon',
    'privacy icon',
    'protect icon',
    'registered icon',
    'remove from calendar icon',
    'search icon',
    'setting icon',
    'settings icon',
    'shop icon',
    'shopping bag icon',
    'shopping basket icon',
    'sidebar icon',
    'signal icon',
    'sitemap icon',
    'tag icon',
    'tags icon',
    'tasks icon',
    'terminal icon',
    'text telephone icon',
    'ticket icon',
    'trademark icon',
    'trophy icon',
    'window close icon',
    'window close outline icon',
    'window maximize icon',
    'window minimize icon',
    'window restore icon',
    'add to cart icon',
    'add user icon',
    'adjust icon',
    'archive icon',
    'ban icon',
    'bookmark icon',
    'call icon',
    'call square icon',
    'clone icon',
    'cloud download icon',
    'cloud upload icon',
    'talk icon',
    'talk outline icon',
    'compress icon',
    'configure icon',
    'download icon',
    'edit icon',
    'erase icon',
    'exchange icon',
    'expand icon',
    'external share icon',
    'filter icon',
    'hide icon',
    'in cart icon',
    'lock icon',
    'mail forward icon',
    'object group icon',
    'object ungroup icon',
    'pin icon',
    'print icon',
    'random icon',
    'recycle icon',
    'refresh icon',
    'remove bookmark icon',
    'remove user icon',
    'repeat icon',
    'reply all icon',
    'reply icon',
    'retweet icon',
    'send icon',
    'send outline icon',
    'share alternate icon',
    'share alternate square icon',
    'share icon',
    'share square icon',
    'sign in icon',
    'sign out icon',
    'theme icon',
    'translate icon',
    'undo icon',
    'unhide icon',
    'unlock alternate icon',
    'unlock icon',
    'upload icon',
    'wait icon',
    'wizard icon',
    'write icon',
    'write square icon',
    'announcement icon',
    'birthday icon',
    'help circle icon',
    'help icon',
    'info circle icon',
    'info icon',
    'warning circle icon',
    'warning icon',
    'warning sign icon',
    'child icon',
    'doctor icon',
    'handicap icon',
    'spy icon',
    'student icon',
    'user icon',
    'user circle',
    'user circle outline',
    'user outline',
    'users icon',
    'female icon',
    'gay icon',
    'genderless icon',
    'heterosexual icon',
    'intergender icon',
    'lesbian icon',
    'male icon',
    'man icon',
    'neuter icon',
    'non binary transgender icon',
    'other gender horizontal icon',
    'other gender icon',
    'other gender vertical icon',
    'transgender icon',
    'woman icon',
    'block layout icon',
    'crop icon',
    'grid layout icon',
    'list layout icon',
    'maximize icon',
    'resize horizontal icon',
    'resize vertical icon',
    'zoom icon',
    'zoom out icon',
    'anchor icon',
    'bar icon',
    'bathtub icon',
    'bomb icon',
    'book icon',
    'bullseye icon',
    'calculator icon',
    'cocktail icon',
    'diamond icon',
    'fax icon',
    'fire extinguisher icon',
    'fire icon',
    'flag checkered icon',
    'flag icon',
    'flag outline icon',
    'gift icon',
    'hand lizard icon',
    'hand peace icon',
    'hand paper icon',
    'hand rock icon',
    'hand scissors icon',
    'hand spock icon',
    'law icon',
    'leaf icon',
    'legal icon',
    'lemon icon',
    'life ring icon',
    'lightning icon',
    'magnet icon',
    'money icon',
    'moon icon',
    'plane icon',
    'puzzle icon',
    'road icon',
    'rocket icon',
    'shipping icon',
    'shower icon',
    'snowflake icon',
    'soccer icon',
    'sticky note icon',
    'sticky note outline icon',
    'suitcase icon',
    'sun icon',
    'thermometer empty icon',
    'thermometer quarter icon',
    'thermometer half icon',
    'thermometer three quarters icon',
    'thermometer full icon',
    'travel icon',
    'treatment icon',
    'tv icon',
    'umbrella icon',
    'world icon',
    'asterisk icon',
    'certificate icon',
    'circle icon',
    'circle notched icon',
    'circle thin icon',
    'crosshairs icon',
    'cube icon',
    'cubes icon',
    'ellipsis horizontal icon',
    'ellipsis vertical icon',
    'quote left icon',
    'quote right icon',
    'spinner icon',
    'square icon',
    'square outline icon',
    'add circle icon',
    'add square icon',
    'check circle icon',
    'check circle outline icon',
    'check square icon',
    'checkmark box icon',
    'checkmark icon',
    'minus circle icon',
    'minus icon',
    'minus square icon',
    'minus square outline icon',
    'move icon',
    'plus icon',
    'plus square outline icon',
    'radio icon',
    'remove circle icon',
    'remove circle outline icon',
    'remove icon',
    'selected radio icon',
    'toggle off icon',
    'toggle on icon',
    'area chart icon',
    'bar chart icon',
    'camera retro icon',
    'film icon',
    'line chart icon',
    'newspaper icon',
    'photo icon',
    'pie chart icon',
    'sound icon',
    'angle double down icon',
    'angle double left icon',
    'angle double right icon',
    'angle double up icon',
    'angle down icon',
    'angle left icon',
    'angle right icon',
    'angle up icon',
    'arrow circle down icon',
    'arrow circle left icon',
    'arrow circle outline down icon',
    'arrow circle outline left icon',
    'arrow circle outline right icon',
    'arrow circle outline up icon',
    'arrow circle right icon',
    'arrow circle up icon',
    'arrow down icon',
    'arrow left icon',
    'arrow right icon',
    'arrow up icon',
    'caret down icon',
    'caret left icon',
    'caret right icon',
    'caret up icon',
    'chevron circle down icon',
    'chevron circle left icon',
    'chevron circle right icon',
    'chevron circle up icon',
    'chevron down icon',
    'chevron left icon',
    'chevron right icon',
    'chevron up icon',
    'long arrow down icon',
    'long arrow left icon',
    'long arrow right icon',
    'long arrow up icon',
    'pointing down icon',
    'pointing left icon',
    'pointing right icon',
    'pointing up icon',
    'toggle down icon',
    'toggle left icon',
    'toggle right icon',
    'toggle up icon',
    'mobile icon',
    'tablet icon',
    'battery empty icon',
    'battery low icon',
    'battery medium icon',
    'battery high icon',
    'battery full icon',
    'desktop icon',
    'disk outline icon',
    'game icon',
    'keyboard icon',
    'laptop icon',
    'plug icon',
    'power icon',
    'file archive outline icon',
    'file audio outline icon',
    'file code outline icon',
    'file excel outline icon',
    'file icon',
    'file image outline icon',
    'file outline icon',
    'file pdf outline icon',
    'file powerpoint outline icon',
    'file text icon',
    'file text outline icon',
    'file video outline icon',
    'file word outline icon',
    'folder icon',
    'folder open icon',
    'folder open outline icon',
    'folder outline icon',
    'level down icon',
    'level up icon',
    'trash icon',
    'trash outline icon',
    'barcode icon',
    'bluetooth alternative icon',
    'bluetooth icon',
    'css3 icon',
    'database icon',
    'fork icon',
    'html5 icon',
    'microchip icon',
    'openid icon',
    'qrcode icon',
    'rss icon',
    'rss square icon',
    'server icon',
    'usb icon',
    'empty heart icon',
    'empty star icon',
    'frown icon',
    'heart icon',
    'meh icon',
    'smile icon',
    'star half empty icon',
    'star half icon',
    'star icon',
    'thumbs down icon',
    'thumbs outline down icon',
    'thumbs outline up icon',
    'thumbs up icon',
    'backward icon',
    'closed captioning icon',
    'eject icon',
    'fast backward icon',
    'fast forward icon',
    'forward icon',
    'music icon',
    'mute icon',
    'pause circle icon',
    'pause circle outline icon',
    'pause icon',
    'play icon',
    'record icon',
    'step backward icon',
    'step forward icon',
    'stop circle icon',
    'stop circle outline icon',
    'stop icon',
    'unmute icon',
    'video play icon',
    'video play outline icon',
    'volume down icon',
    'volume off icon',
    'volume up icon',
    'bicycle icon',
    'building icon',
    'building outline icon',
    'bus icon',
    'car icon',
    'coffee icon',
    'compass icon',
    'emergency icon',
    'first aid icon',
    'food icon',
    'h icon',
    'hospital icon',
    'hotel icon',
    'location arrow icon',
    'map icon',
    'map outline icon',
    'map pin icon',
    'map signs icon',
    'marker icon',
    'military icon',
    'motorcycle icon',
    'paw icon',
    'ship icon',
    'space shuttle icon',
    'spoon icon',
    'street view icon',
    'subway icon',
    'taxi icon',
    'train icon',
    'television icon',
    'tree icon',
    'university icon',
    'columns icon',
    'sort alphabet ascending icon',
    'sort alphabet descending icon',
    'sort ascending icon',
    'sort content ascending icon',
    'sort content descending icon',
    'sort descending icon',
    'sort icon',
    'sort numeric ascending icon',
    'sort numeric descending icon',
    'table icon',
    'bitcoin icon',
    'dollar icon',
    'euro icon',
    'lira icon',
    'pound icon',
    'ruble icon',
    'rupee icon',
    'shekel icon',
    'won icon',
    'yen icon',
    'wheelchair icon',
    'asl interpreting icon',
    'assistive listening systems icon',
    'audio description icon',
    'blind icon',
    'braille icon',
    'deafness icon',
    'low vision icon',
    'sign language icon',
    'universal access icon',
    'volume control phone icon',
    'align center icon',
    'align justify icon',
    'align left icon',
    'align right icon',
    'attach icon',
    'bold icon',
    'copy icon',
    'cut icon',
    'font icon',
    'header icon',
    'indent icon',
    'italic icon',
    'linkify icon',
    'list icon',
    'ordered list icon',
    'outdent icon',
    'paragraph icon',
    'paste icon',
    'save icon',
    'strikethrough icon',
    'subscript icon',
    'superscript icon',
    'text cursor icon',
    'text height icon',
    'text width icon',
    'underline icon',
    'unlinkify icon',
    'unordered list icon',
]

let faIcons = [
    'abacus',
    'acorn',
    'ad',
    'address-book',
    'address-card',
    'adjust',
    'air-freshener',
    'alarm-clock',
    'alicorn',
    'align-center',
    'align-justify',
    'align-left',
    'align-right',
    'allergies',
    'ambulance',
    'american-sign-language-interpreting',
    'analytics',
    'anchor',
    'angle-double-down',
    'angle-double-left',
    'angle-double-right',
    'angle-double-up',
    'angle-down',
    'angle-left',
    'angle-right',
    'angle-up',
    'angry',
    'ankh',
    'apple-alt',
    'apple-crate',
    'archive',
    'archway',
    'arrow-alt-circle-down',
    'arrow-alt-circle-left',
    'arrow-alt-circle-right',
    'arrow-alt-circle-up',
    'arrow-alt-down',
    'arrow-alt-from-bottom',
    'arrow-alt-from-left',
    'arrow-alt-from-right',
    'arrow-alt-from-top',
    'arrow-alt-left',
    'arrow-alt-right',
    'arrow-alt-square-down',
    'arrow-alt-square-left',
    'arrow-alt-square-right',
    'arrow-alt-square-up',
    'arrow-alt-to-bottom',
    'arrow-alt-to-left',
    'arrow-alt-to-right',
    'arrow-alt-to-top',
    'arrow-alt-up',
    'arrow-circle-down',
    'arrow-circle-left',
    'arrow-circle-right',
    'arrow-circle-up',
    'arrow-down',
    'arrow-from-bottom',
    'arrow-from-left',
    'arrow-from-right',
    'arrow-from-top',
    'arrow-left',
    'arrow-right',
    'arrow-square-down',
    'arrow-square-left',
    'arrow-square-right',
    'arrow-square-up',
    'arrow-to-bottom',
    'arrow-to-left',
    'arrow-to-right',
    'arrow-to-top',
    'arrow-up',
    'arrows-alt-h',
    'arrows-alt-v',
    'arrows-alt',
    'arrows-h',
    'arrows-v',
    'arrows',
    'assistive-listening-systems',
    'asterisk',
    'at',
    'atlas',
    'atom-alt',
    'atom',
    'audio-description',
    'award',
    'axe-battle',
    'axe',
    'backpack',
    'backspace',
    'backward',
    'badge-check',
    'badge-dollar',
    'badge-percent',
    'badge',
    'badger-honey',
    'balance-scale-left',
    'balance-scale-right',
    'balance-scale',
    'ballot-check',
    'ballot',
    'ban',
    'band-aid',
    'barcode-alt',
    'barcode-read',
    'barcode-scan',
    'barcode',
    'bars',
    'baseball-ball',
    'baseball',
    'basketball-ball',
    'basketball-hoop',
    'bat',
    'bath',
    'battery-bolt',
    'battery-empty',
    'battery-full',
    'battery-half',
    'battery-quarter',
    'battery-slash',
    'battery-three-quarters',
    'bed',
    'beer',
    'bell-school-slash',
    'bell-school',
    'bell-slash',
    'bell',
    'bezier-curve',
    'bible',
    'bicycle',
    'binoculars',
    'birthday-cake',
    'blanket',
    'blender-phone',
    'blender',
    'blind',
    'bold',
    'bolt',
    'bomb',
    'bone-break',
    'bone',
    'bong',
    'book-alt',
    'book-dead',
    'book-heart',
    'book-open',
    'book-reader',
    'book-spells',
    'book',
    'bookmark',
    'books',
    'booth-curtain',
    'bow-arrow',
    'bowling-ball',
    'bowling-pins',
    'box-alt',
    'box-ballot',
    'box-check',
    'box-fragile',
    'box-full',
    'box-heart',
    'box-open',
    'box-up',
    'box-usd',
    'box',
    'boxes-alt',
    'boxes',
    'boxing-glove',
    'braille',
    'brain',
    'briefcase-medical',
    'briefcase',
    'broadcast-tower',
    'broom',
    'browser',
    'brush',
    'bug',
    'building',
    'bullhorn',
    'bullseye-arrow',
    'bullseye-pointer',
    'bullseye',
    'burn',
    'bus-alt',
    'bus-school',
    'bus',
    'business-time',
    'cabinet-filing',
    'calculator-alt',
    'calculator',
    'calendar-alt',
    'calendar-check',
    'calendar-edit',
    'calendar-exclamation',
    'calendar-minus',
    'calendar-plus',
    'calendar-star',
    'calendar-times',
    'calendar',
    'camera-alt',
    'camera-retro',
    'camera',
    'campfire',
    'campground',
    'candle-holder',
    'candy-corn',
    'cannabis',
    'capsules',
    'car-alt',
    'car-battery',
    'car-bump',
    'car-crash',
    'car-garage',
    'car-mechanic',
    'car-side',
    'car-tilt',
    'car-wash',
    'car',
    'caret-circle-down',
    'caret-circle-left',
    'caret-circle-right',
    'caret-circle-up',
    'caret-down',
    'caret-left',
    'caret-right',
    'caret-square-down',
    'caret-square-left',
    'caret-square-right',
    'caret-square-up',
    'caret-up',
    'cart-arrow-down',
    'cart-plus',
    'cat',
    'cauldron',
    'certificate',
    'chair-office',
    'chair',
    'chalkboard-teacher',
    'chalkboard',
    'charging-station',
    'chart-area',
    'chart-bar',
    'chart-line-down',
    'chart-line',
    'chart-pie-alt',
    'chart-pie',
    'check-circle',
    'check-double',
    'check-square',
    'check',
    'chess-bishop-alt',
    'chess-bishop',
    'chess-board',
    'chess-clock-alt',
    'chess-clock',
    'chess-king-alt',
    'chess-king',
    'chess-knight-alt',
    'chess-knight',
    'chess-pawn-alt',
    'chess-pawn',
    'chess-queen-alt',
    'chess-queen',
    'chess-rook-alt',
    'chess-rook',
    'chess',
    'chevron-circle-down',
    'chevron-circle-left',
    'chevron-circle-right',
    'chevron-circle-up',
    'chevron-double-down',
    'chevron-double-left',
    'chevron-double-right',
    'chevron-double-up',
    'chevron-down',
    'chevron-left',
    'chevron-right',
    'chevron-square-down',
    'chevron-square-left',
    'chevron-square-right',
    'chevron-square-up',
    'chevron-up',
    'child',
    'church',
    'circle-notch',
    'circle',
    'city',
    'claw-marks',
    'clipboard-check',
    'clipboard-list-check',
    'clipboard-list',
    'clipboard-prescription',
    'clipboard',
    'clock',
    'clone',
    'closed-captioning',
    'cloud-download-alt',
    'cloud-download',
    'cloud-drizzle',
    'cloud-hail-mixed',
    'cloud-hail',
    'cloud-meatball',
    'cloud-moon-rain',
    'cloud-moon',
    'cloud-rain',
    'cloud-rainbow',
    'cloud-showers-heavy',
    'cloud-showers',
    'cloud-sleet',
    'cloud-snow',
    'cloud-sun-rain',
    'cloud-sun',
    'cloud-upload-alt',
    'cloud-upload',
    'cloud',
    'clouds-moon',
    'clouds-sun',
    'clouds',
    'club',
    'cocktail',
    'code-branch',
    'code-commit',
    'code-merge',
    'code',
    'coffee-togo',
    'coffee',
    'coffin',
    'cog',
    'cogs',
    'coins',
    'columns',
    'comment-alt-check',
    'comment-alt-dollar',
    'comment-alt-dots',
    'comment-alt-edit',
    'comment-alt-exclamation',
    'comment-alt-lines',
    'comment-alt-minus',
    'comment-alt-plus',
    'comment-alt-slash',
    'comment-alt-smile',
    'comment-alt-times',
    'comment-alt',
    'comment-check',
    'comment-dollar',
    'comment-dots',
    'comment-edit',
    'comment-exclamation',
    'comment-lines',
    'comment-minus',
    'comment-plus',
    'comment-slash',
    'comment-smile',
    'comment-times',
    'comment',
    'comments-alt-dollar',
    'comments-alt',
    'comments-dollar',
    'comments',
    'compact-disc',
    'compass-slash',
    'compass',
    'compress-alt',
    'compress-wide',
    'compress',
    'concierge-bell',
    'container-storage',
    'conveyor-belt-alt',
    'conveyor-belt',
    'cookie-bite',
    'cookie',
    'copy',
    'copyright',
    'corn',
    'couch',
    'cow',
    'credit-card-blank',
    'credit-card-front',
    'credit-card',
    'cricket',
    'crop-alt',
    'crop',
    'cross',
    'crosshairs',
    'crow',
    'crown',
    'cube',
    'cubes',
    'curling',
    'cut',
    'dagger',
    'database',
    'deaf',
    'democrat',
    'desktop-alt',
    'desktop',
    'dewpoint',
    'dharmachakra',
    'diagnoses',
    'diamond',
    'dice-d10',
    'dice-d12',
    'dice-d20',
    'dice-d4',
    'dice-d6',
    'dice-d8',
    'dice-five',
    'dice-four',
    'dice-one',
    'dice-six',
    'dice-three',
    'dice-two',
    'dice',
    'digital-tachograph',
    'diploma',
    'directions',
    'divide',
    'dizzy',
    'dna',
    'do-not-enter',
    'dog-leashed',
    'dog',
    'dollar-sign',
    'dolly-empty',
    'dolly-flatbed-alt',
    'dolly-flatbed-empty',
    'dolly-flatbed',
    'dolly',
    'donate',
    'door-closed',
    'door-open',
    'dot-circle',
    'dove',
    'download',
    'drafting-compass',
    'dragon',
    'draw-circle',
    'draw-polygon',
    'draw-square',
    'drum-steelpan',
    'drum',
    'drumstick-bite',
    'drumstick',
    'duck',
    'dumbbell',
    'dungeon',
    'ear',
    'eclipse-alt',
    'eclipse',
    'edit',
    'eject',
    'elephant',
    'ellipsis-h-alt',
    'ellipsis-h',
    'ellipsis-v-alt',
    'ellipsis-v',
    'empty-set',
    'engine-warning',
    'envelope-open-dollar',
    'envelope-open-text',
    'envelope-open',
    'envelope-square',
    'envelope',
    'equals',
    'eraser',
    'euro-sign',
    'exchange-alt',
    'exchange',
    'exclamation-circle',
    'exclamation-square',
    'exclamation-triangle',
    'exclamation',
    'expand-alt',
    'expand-arrows-alt',
    'expand-arrows',
    'expand-wide',
    'expand',
    'external-link-alt',
    'external-link-square-alt',
    'external-link-square',
    'external-link',
    'eye-dropper',
    'eye-evil',
    'eye-slash',
    'eye',
    'fast-backward',
    'fast-forward',
    'fax',
    'feather-alt',
    'feather',
    'female',
    'field-hockey',
    'fighter-jet',
    'file-alt',
    'file-archive',
    'file-audio',
    'file-certificate',
    'file-chart-line',
    'file-chart-pie',
    'file-check',
    'file-code',
    'file-contract',
    'file-csv',
    'file-download',
    'file-edit',
    'file-excel',
    'file-exclamation',
    'file-export',
    'file-image',
    'file-import',
    'file-invoice-dollar',
    'file-invoice',
    'file-medical-alt',
    'file-medical',
    'file-minus',
    'file-pdf',
    'file-plus',
    'file-powerpoint',
    'file-prescription',
    'file-signature',
    'file-spreadsheet',
    'file-times',
    'file-upload',
    'file-user',
    'file-video',
    'file-word',
    'file',
    'fill-drip',
    'fill',
    'film-alt',
    'film',
    'filter',
    'fingerprint',
    'fire-extinguisher',
    'fire-smoke',
    'fire',
    'first-aid',
    'fish',
    'fist-raised',
    'flag-alt',
    'flag-checkered',
    'flag-usa',
    'flag',
    'flame',
    'flask-poison',
    'flask-potion',
    'flask',
    'flushed',
    'fog',
    'folder-minus',
    'folder-open',
    'folder-plus',
    'folder-times',
    'folder',
    'folders',
    'font',
    'football-ball',
    'football-helmet',
    'forklift',
    'forward',
    'fragile',
    'frog',
    'frown-open',
    'frown',
    'function',
    'funnel-dollar',
    'futbol',
    'gamepad',
    'gas-pump-slash',
    'gas-pump',
    'gavel',
    'gem',
    'genderless',
    'ghost',
    'gift-card',
    'gift',
    'glass-martini-alt',
    'glass-martini',
    'glasses-alt',
    'glasses',
    'globe-africa',
    'globe-americas',
    'globe-asia',
    'globe-stand',
    'globe',
    'golf-ball',
    'golf-club',
    'gopuram',
    'graduation-cap',
    'greater-than-equal',
    'greater-than',
    'grimace',
    'grin-alt',
    'grin-beam-sweat',
    'grin-beam',
    'grin-hearts',
    'grin-squint-tears',
    'grin-squint',
    'grin-stars',
    'grin-tears',
    'grin-tongue-squint',
    'grin-tongue-wink',
    'grin-tongue',
    'grin-wink',
    'grin',
    'grip-horizontal',
    'grip-vertical',
    'h-square',
    'h1',
    'h2',
    'h3',
    'hammer-war',
    'hammer',
    'hamsa',
    'hand-heart',
    'hand-holding-box',
    'hand-holding-heart',
    'hand-holding-magic',
    'hand-holding-seedling',
    'hand-holding-usd',
    'hand-holding-water',
    'hand-holding',
    'hand-lizard',
    'hand-paper',
    'hand-peace',
    'hand-point-down',
    'hand-point-left',
    'hand-point-right',
    'hand-point-up',
    'hand-pointer',
    'hand-receiving',
    'hand-rock',
    'hand-scissors',
    'hand-spock',
    'hands-heart',
    'hands-helping',
    'hands-usd',
    'hands',
    'handshake-alt',
    'handshake',
    'hanukiah',
    'hashtag',
    'hat-witch',
    'hat-wizard',
    'haykal',
    'hdd',
    'head-side',
    'head-vr',
    'heading',
    'headphones-alt',
    'headphones',
    'headset',
    'heart-circle',
    'heart-rate',
    'heart-square',
    'heart',
    'heartbeat',
    'helicopter',
    'helmet-battle',
    'hexagon',
    'highlighter',
    'hiking',
    'hippo',
    'history',
    'hockey-mask',
    'hockey-puck',
    'hockey-sticks',
    'home-heart',
    'home',
    'hood-cloak',
    'horse',
    'hospital-alt',
    'hospital-symbol',
    'hospital',
    'hot-tub',
    'hotel',
    'hourglass-end',
    'hourglass-half',
    'hourglass-start',
    'hourglass',
    'house-damage',
    'house-flood',
    'hryvnia',
    'humidity',
    'hurricane',
    'i-cursor',
    'id-badge',
    'id-card-alt',
    'id-card',
    'image',
    'images',
    'inbox-in',
    'inbox-out',
    'inbox',
    'indent',
    'industry-alt',
    'industry',
    'infinity',
    'info-circle',
    'info-square',
    'info',
    'inhaler',
    'integral',
    'intersection',
    'inventory',
    'italic',
    'jack-o-lantern',
    'jedi',
    'joint',
    'journal-whills',
    'kaaba',
    'key-skeleton',
    'key',
    'keyboard',
    'keynote',
    'khanda',
    'kidneys',
    'kiss-beam',
    'kiss-wink-heart',
    'kiss',
    'kite',
    'kiwi-bird',
    'knife-kitchen',
    'lambda',
    'lamp',
    'landmark-alt',
    'landmark',
    'language',
    'laptop-code',
    'laptop',
    'laugh-beam',
    'laugh-squint',
    'laugh-wink',
    'laugh',
    'layer-group',
    'layer-minus',
    'layer-plus',
    'leaf-heart',
    'leaf-maple',
    'leaf-oak',
    'leaf',
    'lemon',
    'less-than-equal',
    'less-than',
    'level-down-alt',
    'level-down',
    'level-up-alt',
    'level-up',
    'life-ring',
    'lightbulb-dollar',
    'lightbulb-exclamation',
    'lightbulb-on',
    'lightbulb-slash',
    'lightbulb',
    'link',
    'lips',
    'lira-sign',
    'list-alt',
    'list-ol',
    'list-ul',
    'list',
    'location-arrow',
    'location-circle',
    'location-slash',
    'location',
    'lock-alt',
    'lock-open-alt',
    'lock-open',
    'lock',
    'long-arrow-alt-down',
    'long-arrow-alt-left',
    'long-arrow-alt-right',
    'long-arrow-alt-up',
    'long-arrow-down',
    'long-arrow-left',
    'long-arrow-right',
    'long-arrow-up',
    'loveseat',
    'low-vision',
    'luchador',
    'luggage-cart',
    'lungs',
    'mace',
    'magic',
    'magnet',
    'mail-bulk',
    'male',
    'mandolin',
    'map-marked-alt',
    'map-marked',
    'map-marker-alt-slash',
    'map-marker-alt',
    'map-marker-check',
    'map-marker-edit',
    'map-marker-exclamation',
    'map-marker-minus',
    'map-marker-plus',
    'map-marker-question',
    'map-marker-slash',
    'map-marker-smile',
    'map-marker-times',
    'map-marker',
    'map-pin',
    'map-signs',
    'map',
    'marker',
    'mars-double',
    'mars-stroke-h',
    'mars-stroke-v',
    'mars-stroke',
    'mars',
    'mask',
    'medal',
    'medkit',
    'megaphone',
    'meh-blank',
    'meh-rolling-eyes',
    'meh',
    'memory',
    'menorah',
    'mercury',
    'meteor',
    'microchip',
    'microphone-alt-slash',
    'microphone-alt',
    'microphone-slash',
    'microphone',
    'microscope',
    'mind-share',
    'minus-circle',
    'minus-hexagon',
    'minus-octagon',
    'minus-square',
    'minus',
    'mobile-alt',
    'mobile-android-alt',
    'mobile-android',
    'mobile',
    'money-bill-alt',
    'money-bill-wave-alt',
    'money-bill-wave',
    'money-bill',
    'money-check-alt',
    'money-check',
    'monitor-heart-rate',
    'monkey',
    'monument',
    'moon-cloud',
    'moon-stars',
    'moon',
    'mortar-pestle',
    'mosque',
    'motorcycle',
    'mountain',
    'mountains',
    'mouse-pointer',
    'music',
    'narwhal',
    'network-wired',
    'neuter',
    'newspaper',
    'not-equal',
    'notes-medical',
    'object-group',
    'object-ungroup',
    'octagon',
    'oil-can',
    'oil-temp',
    'om',
    'omega',
    'otter',
    'outdent',
    'paint-brush-alt',
    'paint-brush',
    'paint-roller',
    'palette',
    'pallet-alt',
    'pallet',
    'paper-plane',
    'paperclip',
    'parachute-box',
    'paragraph',
    'parking-circle-slash',
    'parking-circle',
    'parking-slash',
    'parking',
    'passport',
    'pastafarianism',
    'paste',
    'pause-circle',
    'pause',
    'paw-alt',
    'paw-claws',
    'paw',
    'peace',
    'pegasus',
    'pen-alt',
    'pen-fancy',
    'pen-nib',
    'pen-square',
    'pen',
    'pencil-alt',
    'pencil-paintbrush',
    'pencil-ruler',
    'pencil',
    'pennant',
    'people-carry',
    'percent',
    'percentage',
    'person-booth',
    'person-carry',
    'person-dolly-empty',
    'person-dolly',
    'person-sign',
    'phone-office',
    'phone-plus',
    'phone-slash',
    'phone-square',
    'phone-volume',
    'phone',
    'pi',
    'pie',
    'pig',
    'piggy-bank',
    'pills',
    'place-of-worship',
    'plane-alt',
    'plane-arrival',
    'plane-departure',
    'plane',
    'play-circle',
    'play',
    'plug',
    'plus-circle',
    'plus-hexagon',
    'plus-octagon',
    'plus-square',
    'plus',
    'podcast',
    'podium-star',
    'podium',
    'poll-h',
    'poll-people',
    'poll',
    'poo-storm',
    'poo',
    'poop',
    'portrait',
    'pound-sign',
    'power-off',
    'pray',
    'praying-hands',
    'prescription-bottle-alt',
    'prescription-bottle',
    'prescription',
    'presentation',
    'print-slash',
    'print',
    'procedures',
    'project-diagram',
    'pumpkin',
    'puzzle-piece',
    'qrcode',
    'question-circle',
    'question-square',
    'question',
    'quidditch',
    'quote-left',
    'quote-right',
    'quran',
    'rabbit-fast',
    'rabbit',
    'racquet',
    'rainbow',
    'raindrops',
    'ram',
    'ramp-loading',
    'random',
    'receipt',
    'rectangle-landscape',
    'rectangle-portrait',
    'rectangle-wide',
    'recycle',
    'redo-alt',
    'redo',
    'registered',
    'repeat-1-alt',
    'repeat-1',
    'repeat-alt',
    'repeat',
    'reply-all',
    'reply',
    'republican',
    'retweet-alt',
    'retweet',
    'ribbon',
    'ring',
    'road',
    'robot',
    'rocket',
    'route-highway',
    'route-interstate',
    'route',
    'rss-square',
    'rss',
    'ruble-sign',
    'ruler-combined',
    'ruler-horizontal',
    'ruler-triangle',
    'ruler-vertical',
    'ruler',
    'running',
    'rupee-sign',
    'sad-cry',
    'sad-tear',
    'save',
    'scalpel-path',
    'scalpel',
    'scanner-keyboard',
    'scanner-touchscreen',
    'scanner',
    'scarecrow',
    'school',
    'screwdriver',
    'scroll-old',
    'scroll',
    'scrubber',
    'scythe',
    'search-dollar',
    'search-location',
    'search-minus',
    'search-plus',
    'search',
    'seedling',
    'server',
    'shapes',
    'share-all',
    'share-alt-square',
    'share-alt',
    'share-square',
    'share',
    'sheep',
    'shekel-sign',
    'shield-alt',
    'shield-check',
    'shield-cross',
    'shield',
    'ship',
    'shipping-fast',
    'shipping-timed',
    'shoe-prints',
    'shopping-bag',
    'shopping-basket',
    'shopping-cart',
    'shovel',
    'shower',
    'shredder',
    'shuttle-van',
    'shuttlecock',
    'sigma',
    'sign-in-alt',
    'sign-in',
    'sign-language',
    'sign-out-alt',
    'sign-out',
    'sign',
    'signal-1',
    'signal-2',
    'signal-3',
    'signal-4',
    'signal-alt-1',
    'signal-alt-2',
    'signal-alt-3',
    'signal-alt-slash',
    'signal-alt',
    'signal-slash',
    'signal',
    'signature',
    'sitemap',
    'skeleton',
    'skull-crossbones',
    'skull',
    'slash',
    'sliders-h-square',
    'sliders-h',
    'sliders-v-square',
    'sliders-v',
    'smile-beam',
    'smile-plus',
    'smile-wink',
    'smile',
    'smog',
    'smoke',
    'smoking-ban',
    'smoking',
    'snake',
    'snow-blowing',
    'snowflake',
    'socks',
    'solar-panel',
    'sort-alpha-down',
    'sort-alpha-up',
    'sort-amount-down',
    'sort-amount-up',
    'sort-down',
    'sort-numeric-down',
    'sort-numeric-up',
    'sort-up',
    'sort',
    'spa',
    'space-shuttle',
    'spade',
    'spider-black-widow',
    'spider-web',
    'spider',
    'spinner-third',
    'spinner',
    'splotch',
    'spray-can',
    'square-full',
    'square-root-alt',
    'square-root',
    'square',
    'squirrel',
    'staff',
    'stamp',
    'star-and-crescent',
    'star-exclamation',
    'star-half-alt',
    'star-half',
    'star-of-david',
    'star-of-life',
    'star',
    'stars',
    'steering-wheel',
    'step-backward',
    'step-forward',
    'stethoscope',
    'sticky-note',
    'stomach',
    'stop-circle',
    'stop',
    'stopwatch',
    'store-alt',
    'store',
    'stream',
    'street-view',
    'strikethrough',
    'stroopwafel',
    'subscript',
    'subway',
    'suitcase-rolling',
    'suitcase',
    'sun-cloud',
    'sun-dust',
    'sun-haze',
    'sun',
    'sunrise',
    'sunset',
    'superscript',
    'surprise',
    'swatchbook',
    'swimmer',
    'swimming-pool',
    'sword',
    'swords',
    'synagogue',
    'sync-alt',
    'sync',
    'syringe',
    'table-tennis',
    'table',
    'tablet-alt',
    'tablet-android-alt',
    'tablet-android',
    'tablet-rugged',
    'tablet',
    'tablets',
    'tachometer-alt-average',
    'tachometer-alt-fast',
    'tachometer-alt-fastest',
    'tachometer-alt-slow',
    'tachometer-alt-slowest',
    'tachometer-alt',
    'tachometer-average',
    'tachometer-fast',
    'tachometer-fastest',
    'tachometer-slow',
    'tachometer-slowest',
    'tachometer',
    'tag',
    'tags',
    'tally',
    'tape',
    'tasks',
    'taxi',
    'teeth-open',
    'teeth',
    'temperature-frigid',
    'temperature-high',
    'temperature-hot',
    'temperature-low',
    'tennis-ball',
    'terminal',
    'text-height',
    'text-width',
    'th-large',
    'th-list',
    'th',
    'theater-masks',
    'thermometer-empty',
    'thermometer-full',
    'thermometer-half',
    'thermometer-quarter',
    'thermometer-three-quarters',
    'thermometer',
    'theta',
    'thumbs-down',
    'thumbs-up',
    'thumbtack',
    'thunderstorm-moon',
    'thunderstorm-sun',
    'thunderstorm',
    'ticket-alt',
    'ticket',
    'tilde',
    'times-circle',
    'times-hexagon',
    'times-octagon',
    'times-square',
    'times',
    'tint-slash',
    'tint',
    'tire-flat',
    'tire-pressure-warning',
    'tire-rugged',
    'tire',
    'tired',
    'toggle-off',
    'toggle-on',
    'toilet-paper-alt',
    'toilet-paper',
    'tombstone-alt',
    'tombstone',
    'toolbox',
    'tooth',
    'toothbrush',
    'torah',
    'torii-gate',
    'tornado',
    'tractor',
    'trademark',
    'traffic-cone',
    'traffic-light-go',
    'traffic-light-slow',
    'traffic-light-stop',
    'traffic-light',
    'train',
    'transgender-alt',
    'transgender',
    'trash-alt',
    'trash',
    'treasure-chest',
    'tree-alt',
    'tree',
    'trees',
    'triangle',
    'trophy-alt',
    'trophy',
    'truck-container',
    'truck-couch',
    'truck-loading',
    'truck-monster',
    'truck-moving',
    'truck-pickup',
    'truck-ramp',
    'truck',
    'tshirt',
    'tty',
    'turkey',
    'turtle',
    'tv-retro',
    'tv',
    'umbrella-beach',
    'umbrella',
    'underline',
    'undo-alt',
    'undo',
    'unicorn',
    'union',
    'universal-access',
    'university',
    'unlink',
    'unlock-alt',
    'unlock',
    'upload',
    'usd-circle',
    'usd-square',
    'user-alt-slash',
    'user-alt',
    'user-astronaut',
    'user-chart',
    'user-check',
    'user-circle',
    'user-clock',
    'user-cog',
    'user-crown',
    'user-edit',
    'user-friends',
    'user-graduate',
    'user-injured',
    'user-lock',
    'user-md',
    'user-minus',
    'user-ninja',
    'user-plus',
    'user-secret',
    'user-shield',
    'user-slash',
    'user-tag',
    'user-tie',
    'user-times',
    'user',
    'users-class',
    'users-cog',
    'users-crown',
    'users',
    'utensil-fork',
    'utensil-knife',
    'utensil-spoon',
    'utensils-alt',
    'utensils',
    'value-absolute',
    'vector-square',
    'venus-double',
    'venus-mars',
    'venus',
    'vial',
    'vials',
    'video-plus',
    'video-slash',
    'video',
    'vihara',
    'volcano',
    'volleyball-ball',
    'volume-down',
    'volume-mute',
    'volume-off',
    'volume-slash',
    'volume-up',
    'volume',
    'vote-nay',
    'vote-yea',
    'vr-cardboard',
    'walking',
    'wallet',
    'wand-magic',
    'wand',
    'warehouse-alt',
    'warehouse',
    'watch-fitness',
    'watch',
    'water-lower',
    'water-rise',
    'water',
    'weight-hanging',
    'weight',
    'whale',
    'wheat',
    'wheelchair',
    'whistle',
    'wifi-1',
    'wifi-2',
    'wifi-slash',
    'wifi',
    'wind-warning',
    'wind',
    'window-alt',
    'window-close',
    'window-maximize',
    'window-minimize',
    'window-restore',
    'window',
    'windsock',
    'wine-bottle',
    'wine-glass-alt',
    'wine-glass',
    'won-sign',
    'wrench',
    'x-ray',
    'yen-sign',
    'yin-yang',

]

let faBrand = [
    '500px',
    'accessible-icon',
    'accusoft',
    'acquisitions-incorporated',
    'adn',
    'adversal',
    'affiliatetheme',
    'algolia',
    'alipay',
    'amazon-pay',
    'amazon',
    'amilia',
    'android',
    'angellist',
    'angrycreative',
    'angular',
    'app-store-ios',
    'app-store',
    'apper',
    'apple-pay',
    'apple',
    'asymmetrik',
    'audible',
    'autoprefixer',
    'avianex',
    'aviato',
    'aws',
    'bandcamp',
    'behance-square',
    'behance',
    'bimobject',
    'bitbucket',
    'bitcoin',
    'bity',
    'black-tie',
    'blackberry',
    'blogger-b',
    'blogger',
    'bluetooth-b',
    'bluetooth',
    'btc',
    'buromobelexperte',
    'buysellads',
    'cc-amazon-pay',
    'cc-amex',
    'cc-apple-pay',
    'cc-diners-club',
    'cc-discover',
    'cc-jcb',
    'cc-mastercard',
    'cc-paypal',
    'cc-stripe',
    'cc-visa',
    'centercode',
    'chrome',
    'cloudscale',
    'cloudsmith',
    'cloudversify',
    'codepen',
    'codiepie',
    'connectdevelop',
    'contao',
    'cpanel',
    'creative-commons-by',
    'creative-commons-nc-eu',
    'creative-commons-nc-jp',
    'creative-commons-nc',
    'creative-commons-nd',
    'creative-commons-pd-alt',
    'creative-commons-pd',
    'creative-commons-remix',
    'creative-commons-sa',
    'creative-commons-sampling-plus',
    'creative-commons-sampling',
    'creative-commons-share',
    'creative-commons-zero',
    'creative-commons',
    'critical-role',
    'css3-alt',
    'css3',
    'cuttlefish',
    'd-and-d-beyond',
    'd-and-d',
    'dashcube',
    'delicious',
    'deploydog',
    'deskpro',
    'dev',
    'deviantart',
    'digg',
    'digital-ocean',
    'discord',
    'discourse',
    'dochub',
    'docker',
    'draft2digital',
    'dribbble-square',
    'dribbble',
    'dropbox',
    'drupal',
    'dyalog',
    'earlybirds',
    'ebay',
    'edge',
    'elementor',
    'ello',
    'ember',
    'empire',
    'envira',
    'erlang',
    'ethereum',
    'etsy',
    'expeditedssl',
    'facebook-f',
    'facebook-messenger',
    'facebook-square',
    'facebook',
    'fantasy-flight-games',
    'firefox',
    'first-order-alt',
    'first-order',
    'firstdraft',
    'flickr',
    'flipboard',
    'fly',
    'font-awesome-alt',
    'font-awesome-flag',
    'font-awesome',
    'fonticons-fi',
    'fonticons',
    'fort-awesome-alt',
    'fort-awesome',
    'forumbee',
    'foursquare',
    'free-code-camp',
    'freebsd',
    'fulcrum',
    'galactic-republic',
    'galactic-senate',
    'get-pocket',
    'gg-circle',
    'gg',
    'git-square',
    'git',
    'github-alt',
    'github-square',
    'github',
    'gitkraken',
    'gitlab',
    'gitter',
    'glide-g',
    'glide',
    'gofore',
    'goodreads-g',
    'goodreads',
    'google-drive',
    'google-play',
    'google-plus-g',
    'google-plus-square',
    'google-plus',
    'google-wallet',
    'google',
    'gratipay',
    'grav',
    'gripfire',
    'grunt',
    'gulp',
    'hacker-news-square',
    'hacker-news',
    'hackerrank',
    'hips',
    'hire-a-helper',
    'hooli',
    'hornbill',
    'hotjar',
    'houzz',
    'html5',
    'hubspot',
    'imdb',
    'instagram',
    'internet-explorer',
    'ioxhost',
    'itunes-note',
    'itunes',
    'java',
    'jedi-order',
    'jenkins',
    'joget',
    'joomla',
    'js-square',
    'js',
    'jsfiddle',
    'kaggle',
    'keybase',
    'keycdn',
    'kickstarter-k',
    'kickstarter',
    'korvue',
    'laravel',
    'lastfm-square',
    'lastfm',
    'leanpub',
    'less',
    'line',
    'linkedin-in',
    'linkedin',
    'linode',
    'linux',
    'lyft',
    'magento',
    'mailchimp',
    'mandalorian',
    'markdown',
    'mastodon',
    'maxcdn',
    'medapps',
    'medium-m',
    'medium',
    'medrt',
    'meetup',
    'megaport',
    'microsoft',
    'mix',
    'mixcloud',
    'mizuni',
    'modx',
    'monero',
    'napster',
    'neos',
    'nimblr',
    'nintendo-switch',
    'node-js',
    'node',
    'npm',
    'ns8',
    'nutritionix',
    'odnoklassniki-square',
    'odnoklassniki',
    'old-republic',
    'opencart',
    'openid',
    'opera',
    'optin-monster',
    'osi',
    'page4',
    'pagelines',
    'palfed',
    'patreon',
    'paypal',
    'penny-arcade',
    'periscope',
    'phabricator',
    'phoenix-framework',
    'phoenix-squadron',
    'php',
    'pied-piper-alt',
    'pied-piper-hat',
    'pied-piper-pp',
    'pied-piper',
    'pinterest-p',
    'pinterest-square',
    'pinterest',
    'playstation',
    'product-hunt',
    'pushed',
    'python',
    'qq',
    'quinscape',
    'quora',
    'r-project',
    'ravelry',
    'react',
    'reacteurope',
    'readme',
    'rebel',
    'red-river',
    'reddit-alien',
    'reddit-square',
    'reddit',
    'renren',
    'replyd',
    'researchgate',
    'resolving',
    'rev',
    'rocketchat',
    'rockrms',
    'safari',
    'sass',
    'schlix',
    'scribd',
    'searchengin',
    'sellcast',
    'sellsy',
    'servicestack',
    'shirtsinbulk',
    'shopware',
    'simplybuilt',
    'sistrix',
    'sith',
    'skyatlas',
    'skype',
    'slack-hash',
    'slack',
    'slideshare',
    'snapchat-ghost',
    'snapchat-square',
    'snapchat',
    'soundcloud',
    'speakap',
    'spotify',
    'squarespace',
    'stack-exchange',
    'stack-overflow',
    'staylinked',
    'steam-square',
    'steam-symbol',
    'steam',
    'sticker-mule',
    'strava',
    'stripe-s',
    'stripe',
    'studiovinari',
    'stumbleupon-circle',
    'stumbleupon',
    'superpowers',
    'supple',
    'teamspeak',
    'telegram-plane',
    'telegram',
    'tencent-weibo',
    'the-red-yeti',
    'themeco',
    'themeisle',
    'think-peaks',
    'trade-federation',
    'trello',
    'tripadvisor',
    'tumblr-square',
    'tumblr',
    'twitch',
    'twitter-square',
    'twitter',
    'typo3',
    'uber',
    'uikit',
    'uniregistry',
    'untappd',
    'usb',
    'ussunnah',
    'vaadin',
    'viacoin',
    'viadeo-square',
    'viadeo',
    'viber',
    'vimeo-square',
    'vimeo-v',
    'vimeo',
    'vine',
    'vk',
    'vnv',
    'vuejs',
    'weebly',
    'weibo',
    'weixin',
    'whatsapp-square',
    'whatsapp',
    'whmcs',
    'wikipedia-w',
    'windows',
    'wix',
    'wizards-of-the-coast',
    'wolf-pack-battalion',
    'wordpress-simple',
    'wordpress',
    'wpbeginner',
    'wpexplorer',
    'wpforms',
    'wpressr',
    'xbox',
    'xing-square',
    'xing',
    'y-combinator',
    'yahoo',
    'yandex-international',
    'yandex',
    'yelp',
    'yoast',
    'youtube-square',
    'youtube',
    'zhihu',
];

export { icons, faBrand, faIcons }